first tinger, but first fix AttributeError: module 'tkinter' has no attribute 'Tk' (consider renaming 'C:\dev\code\learning\python\tkinter.py' since it has the same name as the standard library module named 'tkinter' and prevents importing that standard library module). Did you mean: 'tk'?